
import React, { useState } from 'react';
import { ExtractionResult } from '../types';
import { saveExtractionResult, isSupabaseConfigured } from '../services/supabaseService';

interface ResultCardProps {
  result: ExtractionResult;
  onReset: () => void;
}

// Updated SQL for Movie Invoicing System (Migration Friendly)
const SQL_SETUP_CODE = `
-- 1. PROFILES (Links Supabase Auth to your App Users)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  is_superuser boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add is_disabled column if it doesn't exist
do $$ begin
    alter table profiles add column is_disabled boolean default false;
exception
    when duplicate_column then null;
end $$;

-- Trigger to automatically create a profile when a user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, is_superuser)
  values (new.id, new.email, false);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. PROJECTS
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ROLES & ASSIGNMENTS
-- Create enum if it doesn't exist
do $$ begin
    create type project_role as enum ('lineproducer', 'producer', 'accountant');
exception
    when duplicate_object then null;
end $$;

create table if not exists project_assignments (
  id bigint generated by default as identity primary key,
  project_id bigint references projects on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  role project_role not null,
  unique(project_id, user_id)
);

-- 4. INVOICES (Ensures table exists and has new columns)
create table if not exists invoices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  ico text,
  company_name text,
  bank_account text,
  iban text,
  amount_with_vat numeric,
  amount_without_vat numeric,
  currency text,
  confidence float,
  raw_text text
);

-- Add project_id column if it doesn't exist yet
do $$ begin
    alter table invoices add column project_id bigint references projects(id);
exception
    when duplicate_column then null;
end $$;

-- 5. INVITATIONS
create table if not exists user_invitations (
  id bigint generated by default as identity primary key,
  email text not null,
  invited_by uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'pending'
);

-- 6. SECURITY (Row Level Security)
alter table profiles enable row level security;
alter table projects enable row level security;
alter table project_assignments enable row level security;
alter table invoices enable row level security;
alter table user_invitations enable row level security;

-- 7. POLICIES (Drop existing to ensure clean updates)

-- Profiles
drop policy if exists "Read profiles" on profiles;
create policy "Read profiles" on profiles for select to authenticated using (true);

drop policy if exists "Superusers update profiles" on profiles;
create policy "Superusers update profiles" on profiles for update to authenticated 
  using (exists (select 1 from profiles where id = auth.uid() and is_superuser = true));

-- Projects
drop policy if exists "Superusers full projects" on projects;
create policy "Superusers full projects" on projects for all to authenticated 
  using (exists (select 1 from profiles where id = auth.uid() and is_superuser = true));

drop policy if exists "Assigned users read projects" on projects;
create policy "Assigned users read projects" on projects for select to authenticated 
  using (exists (select 1 from project_assignments where user_id = auth.uid() and project_id = projects.id));

-- Assignments
drop policy if exists "Superusers manage assignments" on project_assignments;
create policy "Superusers manage assignments" on project_assignments for all to authenticated 
  using (exists (select 1 from profiles where id = auth.uid() and is_superuser = true));

drop policy if exists "Read own assignments" on project_assignments;
create policy "Read own assignments" on project_assignments for select to authenticated 
  using (user_id = auth.uid());

-- Invoices
drop policy if exists "Users manage own invoices" on invoices;
create policy "Users manage own invoices" on invoices for all to authenticated using (auth.uid() = user_id);

drop policy if exists "Superusers view all invoices" on invoices;
create policy "Superusers view all invoices" on invoices for select to authenticated 
  using (exists (select 1 from profiles where id = auth.uid() and is_superuser = true));

-- Invitations
drop policy if exists "Superusers manage invitations" on user_invitations;
create policy "Superusers manage invitations" on user_invitations for all to authenticated 
  using (exists (select 1 from profiles where id = auth.uid() and is_superuser = true));

-- 8. SET MASTER USER (Run this line explicitly!)
-- update profiles set is_superuser = true where email = 'tadekus@gmail.com';
`.trim();

const ResultCard: React.FC<ResultCardProps> = ({ result, onReset }) => {
  const isFound = result.ico !== null && result.ico !== undefined;
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [showSql, setShowSql] = useState(false);

  const handleSave = async () => {
    setSaveStatus('saving');
    setErrorMessage(null);
    setShowSql(false);
    
    try {
      // For now, save without project ID (null). 
      // In a full implementation, you'd select the project via a dropdown here.
      await saveExtractionResult(result);
      setSaveStatus('success');
    } catch (err: any) {
      setSaveStatus('error');
      if (err.code === '42P01' || err.message?.includes('relation')) {
        setErrorMessage("Database tables missing.");
        setShowSql(true);
      } else if (err.code === '42501') {
         setErrorMessage("Permission denied. Check RLS policies.");
         setShowSql(true);
      } else {
        setErrorMessage(err.message || "Failed to save");
      }
    }
  };

  const formatCurrency = (amount: number | null | undefined, currency: string | null | undefined) => {
    if (amount === null || amount === undefined) return 'N/A';
    try {
      return new Intl.NumberFormat('cs-CZ', {
        style: 'currency',
        currency: currency || 'CZK',
      }).format(amount);
    } catch (e) {
      return `${amount} ${currency || ''}`;
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-xl border border-slate-100 overflow-hidden animate-fade-in-up">
      <div className={`h-2 w-full ${isFound ? 'bg-emerald-500' : 'bg-amber-500'}`} />
      
      <div className="p-8">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold text-slate-800">Extraction Result</h2>
          {result.confidence && (
            <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
              result.confidence > 0.8 ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'
            }`}>
              {Math.round(result.confidence * 100)}% Confidence
            </span>
          )}
        </div>

        {isFound ? (
          <div className="space-y-8">
            <div className="bg-slate-50 p-6 rounded-lg border border-slate-100 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="text-xs uppercase tracking-wide text-slate-500 font-semibold mb-2 block">
                  Supplier IČO
                </label>
                <div className="flex items-center space-x-3">
                  <span className="text-3xl font-mono font-bold text-indigo-600 tracking-tight">
                    {result.ico}
                  </span>
                  <button 
                    onClick={() => { if (result.ico) navigator.clipboard.writeText(result.ico); }}
                    className="p-1.5 hover:bg-slate-200 rounded-full transition-colors text-slate-400 hover:text-indigo-600"
                  >
                     <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 012 2v8a2 2 0 01-2 2h-8a2 2 0 01-2-2v-8a2 2 0 012-2z" />
                    </svg>
                  </button>
                </div>
              </div>
              <div>
                <label className="text-xs uppercase tracking-wide text-slate-500 font-semibold mb-2 block">
                  Company Name
                </label>
                <p className="text-lg text-slate-800 font-medium break-words">
                  {result.companyName || <span className="text-slate-400 italic">Not found</span>}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm">
                 <div className="flex items-center mb-4 text-emerald-600">
                    <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <h3 className="font-semibold">Amounts</h3>
                 </div>
                 <div className="space-y-3">
                   <div className="flex justify-between items-baseline border-b border-slate-100 pb-2">
                     <span className="text-sm text-slate-500">Total (With VAT)</span>
                     <span className="text-xl font-bold text-slate-900">
                       {formatCurrency(result.amountWithVat, result.currency)}
                     </span>
                   </div>
                   <div className="flex justify-between items-baseline">
                     <span className="text-sm text-slate-500">Without VAT</span>
                     <span className="text-base font-medium text-slate-700">
                       {formatCurrency(result.amountWithoutVat, result.currency)}
                     </span>
                   </div>
                 </div>
              </div>
              <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm">
                 <div className="flex items-center mb-4 text-blue-600">
                    <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                    </svg>
                    <h3 className="font-semibold">Bank Details</h3>
                 </div>
                 <div className="space-y-3">
                   <div>
                     <span className="text-xs text-slate-400 block mb-1">Account Number</span>
                     <p className="font-mono text-slate-800 bg-slate-50 p-1.5 rounded text-sm">
                       {result.bankAccount || <span className="text-slate-400 italic">Not found</span>}
                     </p>
                   </div>
                   {result.iban && (
                    <div>
                      <span className="text-xs text-slate-400 block mb-1">IBAN</span>
                      <p className="font-mono text-slate-800 bg-slate-50 p-1.5 rounded text-sm break-all">
                        {result.iban}
                      </p>
                    </div>
                   )}
                 </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center py-8">
            <h3 className="text-lg font-medium text-slate-900 mb-1">IČO Not Found</h3>
            <p className="text-slate-500 max-w-xs mx-auto">
              We analyzed the document but couldn't confidently identify a Czech business ID number.
            </p>
          </div>
        )}

        {/* Database Error & Setup Section */}
        {showSql && (
          <div className="mt-6 bg-slate-800 rounded-lg p-4 text-left animate-fade-in border border-slate-700">
            <div className="flex justify-between items-center mb-3">
              <h4 className="text-slate-200 font-semibold text-sm flex items-center">
                <svg className="w-4 h-4 mr-2 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
                </svg>
                Database Setup (Master User Only)
              </h4>
              <button 
                onClick={() => navigator.clipboard.writeText(SQL_SETUP_CODE)}
                className="text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-2 py-1 rounded transition-colors"
              >
                Copy SQL
              </button>
            </div>
            {!isSupabaseConfigured && (
              <div className="mb-3 p-2 bg-amber-500/10 border border-amber-500/20 rounded text-amber-200 text-xs">
                <strong>Missing Keys:</strong> Set environment variables first.
              </div>
            )}
            <p className="text-slate-400 text-xs mb-2">
              Run this in your Supabase SQL Editor. 
            </p>
            <pre className="text-xs text-emerald-400 font-mono bg-slate-950 p-3 rounded overflow-x-auto border border-slate-800 max-h-64">
              {SQL_SETUP_CODE}
            </pre>
            <div className="mt-2 text-xs text-slate-500">
               *After running, execute manually: <br/>
               <code className="text-indigo-400">update profiles set is_superuser = true where email = 'tadekus@gmail.com';</code>
            </div>
          </div>
        )}

        <div className="mt-8 pt-6 border-t border-slate-100 flex items-center justify-between">
          <div className="flex flex-col">
             <div className="flex items-center space-x-3">
               {isSupabaseConfigured && isFound ? (
                  <button
                    onClick={handleSave}
                    disabled={saveStatus === 'saving' || saveStatus === 'success'}
                    className={`
                      flex items-center px-4 py-2 rounded-lg text-sm font-medium transition-all
                      ${saveStatus === 'success' 
                        ? 'bg-emerald-100 text-emerald-700 cursor-default' 
                        : saveStatus === 'error'
                        ? 'bg-red-100 text-red-700 hover:bg-red-200'
                        : 'bg-indigo-600 text-white hover:bg-indigo-700 shadow-md hover:shadow-lg'}
                      ${saveStatus === 'saving' ? 'opacity-75 cursor-wait' : ''}
                    `}
                  >
                    {saveStatus === 'saving' ? 'Saving...' : saveStatus === 'success' ? 'Saved' : 'Save Invoice'}
                  </button>
               ) : !isSupabaseConfigured && isFound && (
                   <span className="text-xs text-amber-600 bg-amber-50 px-2 py-1 rounded border border-amber-100">Config Missing</span>
               )}
               
               {!showSql && (
                  <button 
                    onClick={() => setShowSql(true)}
                    className="text-xs text-slate-400 hover:text-indigo-500 underline flex items-center"
                  >
                    DB Setup
                  </button>
               )}
             </div>
             {saveStatus === 'error' && errorMessage && (
               <span className="text-xs text-red-500 mt-2">{errorMessage}</span>
             )}
          </div>
          <button onClick={onReset} className="text-sm font-medium text-slate-500 hover:text-indigo-600 transition-colors">
            Process another
          </button>
        </div>
      </div>
    </div>
  );
};

export default ResultCard;
