import React, { useState } from 'react';
import { ExtractionResult } from '../types';
import { saveExtractionResult, isSupabaseConfigured } from '../services/supabaseService';

interface ResultCardProps {
  result: ExtractionResult;
  onReset: () => void;
}

const SQL_SETUP_CODE = `
-- Run this in your Supabase SQL Editor
create table invoices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ico text,
  company_name text,
  bank_account text,
  iban text,
  amount_with_vat numeric,
  amount_without_vat numeric,
  currency text,
  confidence float,
  raw_text text
);
`.trim();

const ResultCard: React.FC<ResultCardProps> = ({ result, onReset }) => {
  const isFound = result.ico !== null && result.ico !== undefined;
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [showSql, setShowSql] = useState(false);

  const handleSave = async () => {
    setSaveStatus('saving');
    setErrorMessage(null);
    setShowSql(false);
    
    try {
      await saveExtractionResult(result);
      setSaveStatus('success');
    } catch (err: any) {
      setSaveStatus('error');
      // Supabase error 42P01 means "relation does not exist" (Table missing)
      if (err.code === '42P01' || err.message?.includes('invoices')) {
        setErrorMessage("Table 'invoices' not found in Supabase.");
        setShowSql(true);
      } else {
        setErrorMessage(err.message || "Failed to save");
      }
    }
  };

  const formatCurrency = (amount: number | null | undefined, currency: string | null | undefined) => {
    if (amount === null || amount === undefined) return 'N/A';
    try {
      return new Intl.NumberFormat('cs-CZ', {
        style: 'currency',
        currency: currency || 'CZK',
      }).format(amount);
    } catch (e) {
      return `${amount} ${currency || ''}`;
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-xl border border-slate-100 overflow-hidden animate-fade-in-up">
      <div className={`h-2 w-full ${isFound ? 'bg-emerald-500' : 'bg-amber-500'}`} />
      
      <div className="p-8">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold text-slate-800">Extraction Result</h2>
          {result.confidence && (
            <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
              result.confidence > 0.8 ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'
            }`}>
              {Math.round(result.confidence * 100)}% Confidence
            </span>
          )}
        </div>

        {isFound ? (
          <div className="space-y-8">
            {/* Identity Section */}
            <div className="bg-slate-50 p-6 rounded-lg border border-slate-100 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="text-xs uppercase tracking-wide text-slate-500 font-semibold mb-2 block">
                  Supplier IČO
                </label>
                <div className="flex items-center space-x-3">
                  <span className="text-3xl font-mono font-bold text-indigo-600 tracking-tight">
                    {result.ico}
                  </span>
                  <button 
                    onClick={() => {
                      if (result.ico) navigator.clipboard.writeText(result.ico);
                    }}
                    className="p-1.5 hover:bg-slate-200 rounded-full transition-colors text-slate-400 hover:text-indigo-600"
                    title="Copy to clipboard"
                  >
                     <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 012 2v8a2 2 0 01-2 2h-8a2 2 0 01-2-2v-8a2 2 0 012-2z" />
                    </svg>
                  </button>
                </div>
              </div>
              
              <div>
                <label className="text-xs uppercase tracking-wide text-slate-500 font-semibold mb-2 block">
                  Company Name
                </label>
                <p className="text-lg text-slate-800 font-medium break-words">
                  {result.companyName || <span className="text-slate-400 italic">Not found</span>}
                </p>
              </div>
            </div>

            {/* Financial Details Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              
              {/* Amounts */}
              <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm">
                 <div className="flex items-center mb-4 text-emerald-600">
                    <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <h3 className="font-semibold">Amounts</h3>
                 </div>
                 
                 <div className="space-y-3">
                   <div className="flex justify-between items-baseline border-b border-slate-100 pb-2">
                     <span className="text-sm text-slate-500">Total (With VAT)</span>
                     <span className="text-xl font-bold text-slate-900">
                       {formatCurrency(result.amountWithVat, result.currency)}
                     </span>
                   </div>
                   <div className="flex justify-between items-baseline">
                     <span className="text-sm text-slate-500">Without VAT</span>
                     <span className="text-base font-medium text-slate-700">
                       {formatCurrency(result.amountWithoutVat, result.currency)}
                     </span>
                   </div>
                 </div>
              </div>

              {/* Bank Details */}
              <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-sm">
                 <div className="flex items-center mb-4 text-blue-600">
                    <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                    </svg>
                    <h3 className="font-semibold">Bank Details</h3>
                 </div>
                 
                 <div className="space-y-3">
                   <div>
                     <span className="text-xs text-slate-400 block mb-1">Account Number</span>
                     <p className="font-mono text-slate-800 bg-slate-50 p-1.5 rounded text-sm">
                       {result.bankAccount || <span className="text-slate-400 italic">Not found</span>}
                     </p>
                   </div>
                   {result.iban && (
                    <div>
                      <span className="text-xs text-slate-400 block mb-1">IBAN</span>
                      <p className="font-mono text-slate-800 bg-slate-50 p-1.5 rounded text-sm break-all">
                        {result.iban}
                      </p>
                    </div>
                   )}
                 </div>
              </div>
            </div>

            {result.rawText && (
               <div className="text-xs text-slate-400 italic mt-2 text-right">
                Detected from: "{result.rawText.substring(0, 50)}..."
              </div>
            )}
          </div>
        ) : (
          <div className="text-center py-8">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-amber-100 mb-4">
               <svg className="w-8 h-8 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <h3 className="text-lg font-medium text-slate-900 mb-1">IČO Not Found</h3>
            <p className="text-slate-500 max-w-xs mx-auto">
              We analyzed the document but couldn't confidently identify a Czech business ID number.
            </p>
          </div>
        )}

        {/* Database Error & Setup Section */}
        {showSql && (
          <div className="mt-6 bg-slate-800 rounded-lg p-4 text-left animate-fade-in border border-slate-700">
            <div className="flex justify-between items-center mb-3">
              <h4 className="text-slate-200 font-semibold text-sm flex items-center">
                <svg className="w-4 h-4 mr-2 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
                </svg>
                Supabase Setup
              </h4>
              <button 
                onClick={() => navigator.clipboard.writeText(SQL_SETUP_CODE)}
                className="text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-2 py-1 rounded transition-colors"
              >
                Copy SQL
              </button>
            </div>
            
            {!isSupabaseConfigured && (
              <div className="mb-3 p-2 bg-amber-500/10 border border-amber-500/20 rounded text-amber-200 text-xs">
                <strong>Missing Keys:</strong> Set <code>SUPABASE_URL</code> and <code>SUPABASE_ANON_KEY</code> in your environment variables first.
              </div>
            )}

            <p className="text-slate-400 text-xs mb-2">
              Run this in your Supabase SQL Editor to create the table:
            </p>
            <pre className="text-xs text-emerald-400 font-mono bg-slate-950 p-3 rounded overflow-x-auto border border-slate-800">
              {SQL_SETUP_CODE}
            </pre>
          </div>
        )}

        <div className="mt-8 pt-6 border-t border-slate-100 flex items-center justify-between">
          <div className="flex flex-col">
             <div className="flex items-center space-x-3">
               {isSupabaseConfigured && isFound ? (
                  <button
                    onClick={handleSave}
                    disabled={saveStatus === 'saving' || saveStatus === 'success'}
                    className={`
                      flex items-center px-4 py-2 rounded-lg text-sm font-medium transition-all
                      ${saveStatus === 'success' 
                        ? 'bg-emerald-100 text-emerald-700 cursor-default' 
                        : saveStatus === 'error'
                        ? 'bg-red-100 text-red-700 hover:bg-red-200'
                        : 'bg-indigo-600 text-white hover:bg-indigo-700 shadow-md hover:shadow-lg'}
                      ${saveStatus === 'saving' ? 'opacity-75 cursor-wait' : ''}
                    `}
                  >
                    {saveStatus === 'saving' && (
                      <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                    )}
                    {saveStatus === 'success' ? (
                      <>
                        <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Saved
                      </>
                    ) : saveStatus === 'error' ? (
                      'Retry Save'
                    ) : (
                      <>
                        <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                        </svg>
                        Save to DB
                      </>
                    )}
                  </button>
               ) : (
                // If Supabase not configured, show a disabled button or nothing
                 !isSupabaseConfigured && isFound && (
                   <span className="text-xs text-amber-600 bg-amber-50 px-2 py-1 rounded border border-amber-100">
                     Supabase Not Configured
                   </span>
                 )
               )}
               
               {/* Manual toggle for SQL help - ALWAYS VISIBLE if not showing already */}
               {!showSql && saveStatus !== 'success' && (
                  <button 
                    onClick={() => setShowSql(true)}
                    className="text-xs text-slate-400 hover:text-indigo-500 underline flex items-center"
                  >
                    <svg className="w-3 h-3 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                       <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                       <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                    DB Setup
                  </button>
               )}
             </div>
             {saveStatus === 'error' && errorMessage && (
               <span className="text-xs text-red-500 mt-2">{errorMessage}</span>
             )}
          </div>

          <button
            onClick={onReset}
            className="text-sm font-medium text-slate-500 hover:text-indigo-600 transition-colors flex items-center"
          >
            <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Process another
          </button>
        </div>
      </div>
    </div>
  );
};

export default ResultCard;